const express=require('express');
const router=express.Router();
const catchAsync=require('../utils/catchAsync');
const Campground=require('../models/campground');
const campgrounds=require('../controllers/campgrounds'); 
const {isLoggedIn, isAuthor,validateCampgroud}=require('../middleware');
const multer  = require('multer');   //https://github.com/expressjs/multer
const {storage}=require('../cloudinary');
const upload = multer({ storage });